name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./HelloWorldBlazorServer/HelloWorldBlazorServer
        
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Current Working Directory
      run: echo ${{ github.workspace }}
    - name: Restore dependencies
      run: dotnet restore 
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: dotnet publish
      run: dotnet publish -c Release -o ${{ github.workspace }}/publish
    - uses: actions/upload-artifact@v3
      with:
        name: Blazor-Server-Artifacts
        path: ${{ github.workspace }}/publish/ # or path/to/artifact      
      
